FROM opi0-stage1

SHELL ["/bin/sh", "-x", "-c"]

RUN rm -rf rootfs

COPY --from=opi0-stage2b / rootfs/

RUN rm rootfs/usr/bin/qemu-arm-static

COPY boot.cmd rootfs/boot/

COPY stage3.sh .

CMD ["/bin/sh", "/stage3.sh"]
