FROM opi0-stage1

SHELL ["/bin/sh", "-x", "-c"]

RUN rm -rf rootfs

COPY --from=opi0-stage2b / rootfs/

RUN rm rootfs/usr/bin/qemu-arm-static

COPY boot.cmd rootfs/boot/

RUN tar c xr819 | tar xC rootfs/lib/firmware
RUN cp /xradio/xradio_wlan.ko rootfs/root/

COPY stage3.sh .

CMD ["/bin/sh", "/stage3.sh"]
