#!/bin/sh

set -eu

RDEV=$(findmnt -l -o SOURCE -f / | sed 1d)
DDEV=${RDEV%p*}

cat <<EOF | flock $DDEV /bin/sh -eu
echo ',+' | sfdisk --no-reread --no-tell-kernel -f $DDEV -N 1
partx -u $DDEV
EOF

mount -o remount,rw /

resize2fs $RDEV

mount -o remount,ro /

exit 0
