#!/bin/sh

set -eux

RDEV=$(findmnt -l -o SOURCE -f / | sed 1d)
DDEV=${RDEV%p*}

cat <<EOF | flock $DDEV /bin/sh -eu
echo ',+' | sfdisk --no-reread --no-tell-kernel -f $DDEV -N 1
partx -vu $DDEV
EOF

mount -o remount,rw /

resize2fs $RDEV

exit 0
